python3 imgs_to_groups_fake.py --imgs_dir 'fake_data/fake_images_CcGAN_hard_nsamp_60000/fake_images_CcGAN_hard_nsamp_60000/'

python3 imgs_to_groups_fake.py --imgs_dir 'fake_data/fake_images_CcGAN_limit_nsamp_60000/fake_images_CcGAN_limit_nsamp_60000/'

python3 imgs_to_groups_fake.py --imgs_dir 'fake_data/fake_images_CcGAN_soft_nsamp_60000/fake_images_CcGAN_soft_nsamp_60000/'

python3 imgs_to_groups_fake.py --imgs_dir 'fake_data/fake_images_cGAN_nclass_40_nsamp_60000/fake_images_cGAN_nclass_40_nsamp_60000/'

python3 imgs_to_groups_fake.py --imgs_dir 'fake_data/fake_images_cGAN_nclass_60_nsamp_60000/fake_images_cGAN_nclass_60_nsamp_60000/'

python3 imgs_to_groups_fake.py --imgs_dir 'fake_data/fake_images_improved_CcGAN_hard_nsamp_60000/fake_images_improved_CcGAN_hard_nsamp_60000/'

python3 imgs_to_groups_fake.py --imgs_dir 'fake_data/fake_images_improved_CcGAN_soft_nsamp_60000/fake_images_improved_CcGAN_soft_nsamp_60000/'
